packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': true
  '@scarf/scarf': false
  '@suites/di.nestjs': true
  '@suites/doubles.jest': true
  argon2: false
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  unrs-resolver: true
