name: Commit tests

on:
  push:
  pull_request:

concurrency:
  group: "commit-tests"
  cancel-in-progress: false

jobs:
  test-api:
    name: API
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared packages
        run: pnpm run init:packages

      - name: Run tests
        run: pnpm --filter api test

  test-web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build shared packages
        run: pnpm run init:packages

      - name: Run tests
        run: pnpm --filter web test -- --watch=false --browsers=ChromeHeadless