name: Build and Push Latest

on:
  release:
    types: [released]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      tags: |
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=semver,pattern={{major}}
        type=raw,value=latest
    secrets: inherit
