name: Build and Push Beta

on:
  release:
    types: [prereleased]

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      tags: |
        type=raw,value=beta
        type=semver,pattern={{version}}
    secrets: inherit
